ledger {
  host = "localhost"
  port = 6865
  auth = NoAuth
}
oauth {}

postgres {
  host = "localhost"
  port = 5432
  database = "pqs"
  schema = "pqs_relational"
  username = "pqs"
  password = ${RELATIONAL_DB_PASSWORD}
  maxConnections = 16
}

filter.contracts = "*"

source.ledger = ${ledger}
target.postgres = ${postgres}
target.schema.autoApply = true
pipeline {
  oauth = ${oauth}
  ledger {
    start = Oldest
    stop = Never
  }
  filter {
    contracts = ${filter.contracts}
    parties = "*"
  }
}

projections {
  assets {
    templates = ["Finance:Main:Asset"]
    promote = ["owner", "amount"]
    queries = [{ filter = ["owner"], order = ["amount desc"] }]
  }
}
